version: '3.8'

services:
  qexpress:
    image: 'mongo'
    container_name: 'qexpress'
    environment:
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: qexpress
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init-db.d/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
      - qexpress:/data/db

volumes:
  qexpress:
    driver: local